-- RJ Tech schema on independent Supabase project

create or replace function public.rjtech_is_admin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce(
    (auth.jwt() -> 'app_metadata' ->> 'rjtech_role') = 'admin',
    false
  );
$$;

revoke all on function public.rjtech_is_admin() from public;
grant execute on function public.rjtech_is_admin() to anon, authenticated;

create table if not exists public.rjtech_products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null check (category in (
    'celulares','notebooks','macbooks','videojuego','televisores','gadgets','audio'
  )),
  price numeric(12,0) not null check (price >= 0),
  old_price numeric(12,0) check (old_price is null or old_price >= 0),
  stock integer not null default 0 check (stock >= 0),
  rating numeric(3,1) not null default 4.5 check (rating >= 0 and rating <= 5),
  reviews integer not null default 0 check (reviews >= 0),
  installments text not null default '',
  description text not null default '',
  tags text[] not null default '{}',
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rjtech_providers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact text not null default '',
  email text not null default '',
  phone text not null default '',
  address text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rjtech_store_config (
  id integer primary key default 1 check (id = 1),
  store_name text not null default 'RJ Tech',
  tagline text not null default '',
  support_email text not null default '',
  support_phone text not null default '',
  currency text not null default 'ARS' check (currency in ('ARS','USD')),
  free_shipping_from numeric(12,0) not null default 0,
  shipping_cost numeric(12,0) not null default 0,
  installments_enabled boolean not null default true,
  max_installments integer not null default 12,
  announcement text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.rjtech_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '',
  email text not null,
  phone text not null default '',
  dni text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rjtech_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.rjtech_profiles (id) on delete cascade,
  label text not null default 'Casa',
  street text not null default '',
  city text not null default '',
  province text not null default '',
  zip text not null default '',
  phone text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.rjtech_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  order_number text not null unique,
  status text not null default 'Procesando' check (status in ('Entregado','En camino','Procesando')),
  subtotal numeric(12,0) not null default 0,
  shipping numeric(12,0) not null default 0,
  total numeric(12,0) not null default 0,
  payment text not null default '',
  address text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.rjtech_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.rjtech_orders (id) on delete cascade,
  product_id bigint references public.rjtech_products (id) on delete set null,
  name text not null,
  qty integer not null check (qty > 0),
  unit_price numeric(12,0) not null,
  line_total numeric(12,0) not null
);

create index if not exists rjtech_products_category_idx on public.rjtech_products (category);
create index if not exists rjtech_addresses_user_idx on public.rjtech_addresses (user_id);
create index if not exists rjtech_orders_user_idx on public.rjtech_orders (user_id);

alter table public.rjtech_products enable row level security;
alter table public.rjtech_providers enable row level security;
alter table public.rjtech_store_config enable row level security;
alter table public.rjtech_profiles enable row level security;
alter table public.rjtech_addresses enable row level security;
alter table public.rjtech_orders enable row level security;
alter table public.rjtech_order_items enable row level security;

drop policy if exists "rjtech_products_select" on public.rjtech_products;
create policy "rjtech_products_select" on public.rjtech_products
  for select to anon, authenticated using (true);

drop policy if exists "rjtech_products_admin_insert" on public.rjtech_products;
create policy "rjtech_products_admin_insert" on public.rjtech_products
  for insert to authenticated with check (public.rjtech_is_admin());

drop policy if exists "rjtech_products_admin_update" on public.rjtech_products;
create policy "rjtech_products_admin_update" on public.rjtech_products
  for update to authenticated
  using (public.rjtech_is_admin())
  with check (public.rjtech_is_admin());

drop policy if exists "rjtech_products_admin_delete" on public.rjtech_products;
create policy "rjtech_products_admin_delete" on public.rjtech_products
  for delete to authenticated using (public.rjtech_is_admin());

drop policy if exists "rjtech_providers_admin_select" on public.rjtech_providers;
create policy "rjtech_providers_admin_select" on public.rjtech_providers
  for select to authenticated using (public.rjtech_is_admin());

drop policy if exists "rjtech_providers_admin_insert" on public.rjtech_providers;
create policy "rjtech_providers_admin_insert" on public.rjtech_providers
  for insert to authenticated with check (public.rjtech_is_admin());

drop policy if exists "rjtech_providers_admin_update" on public.rjtech_providers;
create policy "rjtech_providers_admin_update" on public.rjtech_providers
  for update to authenticated
  using (public.rjtech_is_admin())
  with check (public.rjtech_is_admin());

drop policy if exists "rjtech_providers_admin_delete" on public.rjtech_providers;
create policy "rjtech_providers_admin_delete" on public.rjtech_providers
  for delete to authenticated using (public.rjtech_is_admin());

drop policy if exists "rjtech_config_select" on public.rjtech_store_config;
create policy "rjtech_config_select" on public.rjtech_store_config
  for select to anon, authenticated using (true);

drop policy if exists "rjtech_config_admin_update" on public.rjtech_store_config;
create policy "rjtech_config_admin_update" on public.rjtech_store_config
  for update to authenticated
  using (public.rjtech_is_admin())
  with check (public.rjtech_is_admin());

drop policy if exists "rjtech_config_admin_insert" on public.rjtech_store_config;
create policy "rjtech_config_admin_insert" on public.rjtech_store_config
  for insert to authenticated with check (public.rjtech_is_admin());

drop policy if exists "rjtech_profiles_select_own" on public.rjtech_profiles;
create policy "rjtech_profiles_select_own" on public.rjtech_profiles
  for select to authenticated using ((select auth.uid()) = id);

drop policy if exists "rjtech_profiles_insert_own" on public.rjtech_profiles;
create policy "rjtech_profiles_insert_own" on public.rjtech_profiles
  for insert to authenticated with check ((select auth.uid()) = id);

drop policy if exists "rjtech_profiles_update_own" on public.rjtech_profiles;
create policy "rjtech_profiles_update_own" on public.rjtech_profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "rjtech_addresses_select_own" on public.rjtech_addresses;
create policy "rjtech_addresses_select_own" on public.rjtech_addresses
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "rjtech_addresses_insert_own" on public.rjtech_addresses;
create policy "rjtech_addresses_insert_own" on public.rjtech_addresses
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "rjtech_addresses_update_own" on public.rjtech_addresses;
create policy "rjtech_addresses_update_own" on public.rjtech_addresses
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "rjtech_addresses_delete_own" on public.rjtech_addresses;
create policy "rjtech_addresses_delete_own" on public.rjtech_addresses
  for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "rjtech_orders_select_own" on public.rjtech_orders;
create policy "rjtech_orders_select_own" on public.rjtech_orders
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "rjtech_orders_insert_own" on public.rjtech_orders;
create policy "rjtech_orders_insert_own" on public.rjtech_orders
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "rjtech_order_items_select_own" on public.rjtech_order_items;
create policy "rjtech_order_items_select_own" on public.rjtech_order_items
  for select to authenticated
  using (
    exists (
      select 1 from public.rjtech_orders o
      where o.id = order_id and o.user_id = (select auth.uid())
    )
  );

drop policy if exists "rjtech_order_items_insert_own" on public.rjtech_order_items;
create policy "rjtech_order_items_insert_own" on public.rjtech_order_items
  for insert to authenticated
  with check (
    exists (
      select 1 from public.rjtech_orders o
      where o.id = order_id and o.user_id = (select auth.uid())
    )
  );

grant select on public.rjtech_products to anon, authenticated;
grant insert, update, delete on public.rjtech_products to authenticated;
grant select, insert, update, delete on public.rjtech_providers to authenticated;
grant select on public.rjtech_store_config to anon, authenticated;
grant insert, update on public.rjtech_store_config to authenticated;
grant select, insert, update on public.rjtech_profiles to authenticated;
grant select, insert, update, delete on public.rjtech_addresses to authenticated;
grant select, insert on public.rjtech_orders to authenticated;
grant select, insert on public.rjtech_order_items to authenticated;
grant usage, select on sequence public.rjtech_products_id_seq to authenticated;

create or replace function public.rjtech_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.rjtech_profiles (id, name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.email, '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists rjtech_on_auth_user_created on auth.users;
create trigger rjtech_on_auth_user_created
  after insert on auth.users
  for each row execute function public.rjtech_handle_new_user();

revoke all on function public.rjtech_handle_new_user() from public, anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'rjtech-media',
  'rjtech-media',
  true,
  5242880,
  array['image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "rjtech_media_public_read" on storage.objects;
create policy "rjtech_media_public_read"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'rjtech-media');

drop policy if exists "rjtech_media_admin_insert" on storage.objects;
create policy "rjtech_media_admin_insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'rjtech-media' and public.rjtech_is_admin());

drop policy if exists "rjtech_media_admin_update" on storage.objects;
create policy "rjtech_media_admin_update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'rjtech-media' and public.rjtech_is_admin())
  with check (bucket_id = 'rjtech-media' and public.rjtech_is_admin());

drop policy if exists "rjtech_media_admin_delete" on storage.objects;
create policy "rjtech_media_admin_delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'rjtech-media' and public.rjtech_is_admin());
